services:
    HeatWare.integration.cron.task.heatware_sync:
        class: heatware\integration\cron\task\heatware_sync
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@log'
        calls:
            - [set_name, [cron.task.heatware_sync]]
        tags:
            - { name: cron.task }

    HeatWare.integration.listener:
        class: heatware\integration\event\listener
        tags:
            - { name: event.listener }