imports:
    - { resource: parameters.yml }

services:
    HeatWare.integration.controller:
        class: HeatWare\integration\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    HeatWare.integration.cron.task.heatware_sync:
        class: HeatWare\integration\cron\task\HeatWareSync
        arguments:
            - '@config'
        calls:
            - [set_name, [cron.task.heatware_sync]]
        tags:
            - { name: cron.task }
