services:
    HeatWare.integration.cron.task.HeatWareSync:
        class: heatware\integration\cron\task\HeatWareSync
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@log'
        calls:
            - [set_name, [cron.task.HeatWareSync]]
        tags:
            - { name: cron.task }

    HeatWare.integration.listener:
        class: heatware\integration\event\listener
        tags:
            - { name: event.listener }